const Menu = () => {
    return (
     <>
         <div className="menuH2">
            <h2>Menu</h2>
        </div>

        <div>
            <h3>Specialty Bowls</h3>
        </div>

        <div>
            <ul>
                <li>
                    <h4>The Scrumptious Schwab</h4>
                </li>
                <li>
                    <h4>The Vital Vincent</h4>
                    <p></p>
                </li>
                <li>
                    <h4>The Legendary Lindsey</h4>
                </li>
                <li>
                    <h4>The Tasty Tristan</h4>
                </li>
            </ul>
        </div>
     </>
    )
}

export default Menu;